# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63\x61lculator.proto\x12\ncalculator\"2\n\x07Request\x12\x0b\n\x03\x63\x61l\x18\x01 \x01(\t\x12\x0c\n\x04num1\x18\x02 \x01(\x05\x12\x0c\n\x04num2\x18\x03 \x01(\x05\"\x1a\n\x08Response\x12\x0e\n\x06result\x18\x01 \x01(\t2C\n\nCalculator\x12\x35\n\x06\x43\x61lcul\x12\x13.calculator.Request\x1a\x14.calculator.Response\"\x00\x62\x06proto3')



_REQUEST = DESCRIPTOR.message_types_by_name['Request']
_RESPONSE = DESCRIPTOR.message_types_by_name['Response']
Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.Request)
  })
_sym_db.RegisterMessage(Request)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'calculator_pb2'
  # @@protoc_insertion_point(class_scope:calculator.Response)
  })
_sym_db.RegisterMessage(Response)

_CALCULATOR = DESCRIPTOR.services_by_name['Calculator']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQUEST._serialized_start=32
  _REQUEST._serialized_end=82
  _RESPONSE._serialized_start=84
  _RESPONSE._serialized_end=110
  _CALCULATOR._serialized_start=112
  _CALCULATOR._serialized_end=179
# @@protoc_insertion_point(module_scope)
